# Generated by Django 6.0.2 on 2026-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('gia', models.CharField(default='Liên hệ', max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
    ]
