# Generated by Django 6.0.2 on 2026-08-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('tom_tat', models.TextField(blank=True)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='anh_san_pham',
            field=models.ImageField(blank=True, null=True, upload_to='san_pham/'),
        ),
    ]
