# Generated by Django 6.0.2 on 2026-08-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tintuc_sanpham_anh_san_pham'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='noi_dung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
