# Generated by Django 6.0.2 on 2026-08-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tintuc_noi_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn SEO')),
            ],
            options={
                'verbose_name_plural': '1. Danh mục dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('noi_dung', models.TextField(verbose_name='Nội dung cần tư vấn')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '4. Khách hàng liên hệ',
            },
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name_plural': '2. Sản phẩm & Dự án'},
        ),
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name_plural': '3. Tin tức & Sự kiện'},
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tintuc',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='tin_tuc/'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='san_pham', to='home.danhmuc', verbose_name='Danh mục'),
        ),
    ]
